# Generated by Django 5.2.1 on 2025-05-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='shortcode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
