# Generated by Django 5.2.1 on 2025-05-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0002_qrcode_shortcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='attendee',
            name='last_name',
            field=models.CharField(default='Smith', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qrcode',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
